### ISSUE TITLE
CMake on Haiku

### ISSUE THREAD

**Issue by scribam** [cross-platform-actions/action#103]
I am using this in my workflow:
```
- uses: cross-platform-actions/action@v0.28.0
  with:
    operating_system: haiku
    architecture: x86-64
    version: r1beta5
    environment_variables: CCACHE_DIR
    run: |
      pkgman update -y && pkgman install -y ccache cmake git libao libsdl2 libzip lua miniupnpc ninja libcdio
      cmake -B build -DUSE_LIBCDIO=ON -DCMAKE_BUILD_TYPE=Release -G Ninja
      cmake --build build --config Release
```
and I have the following error:
```
A reboot is necessary to complete the installation process.
/bin/bash: line 2: cmake: command not found
```
https://github.com/scribam/flycast/actions/runs/15190011288/job/42720097656#step:4:331

Is there a way to fix this?

**Comment by jacob-carlborg** [comment]
Hmm, that's inconvenient. Is that the case for all packages on Haiku?

It wouldn't be unreasonable to include CMake in the image, although it's not included for the other platforms. But I can't do this for all packages. 

You can always create a custom image: https://github.com/cross-platform-actions/action?tab=readme-ov-file#custom-vm-image-image_url.

**Comment by scribam** [comment]
Thank you for the quick reply!

After further investigation, I don't have the error if I remove the command `pkgman update -y`. This should be enough for me to do that I want 🙂

**Comment by Xottab-DUTY** [comment]
> A reboot is necessary to complete the installation process.

This is for sure inconvenient...
Is there a functionality to reboot the VM?

**Comment by jacob-carlborg** [comment]
> > A reboot is necessary to complete the installation process.
> 
> This is for sure inconvenient...
> Is there a functionality to reboot the VM?

Unfortunately there's not. Is this necessary for many packages? Currently it should work if you create a custom VM image.

**Comment by Xottab-DUTY** [comment]
> Is this necessary for many packages?

It seems to be not needed in my use case.

**Comment by jacob-carlborg** [comment]
@manxorist I've reopened the issue and made the title more general.

**Comment by jacob-carlborg** [comment]
> Maybe there is nothing cross-platform-actions can sensibly do here, except for recommending a custom image

Perhaps adding support for rebooting the VM?

**Comment by jacob-carlborg** [comment]
@manxorist how would one want the reboot feature to look like?

1. As an explicit step, somehow:

```yaml
- uses: cross-platform-actions/action@v0.28.0
  with:
    operating_system: haiku
    architecture: x86-64
    version: r1beta5
    environment_variables: CCACHE_DIR
    run: |
      pkgman update -y && pkgman install -y ccache cmake git libao libsdl2 libzip lua miniupnpc ninja libcdio

- reboot

- uses: cross-platform-actions/action@v0.28.0
  with:
    operating_system: haiku
    architecture: x86-64
    version: r1beta5
    environment_variables: CCACHE_DIR
    run: |
      cmake -B build -DUSE_LIBCDIO=ON -DCMAKE_BUILD_TYPE=Release -G Ninja
      cmake --build build --config Release
```

2. Or a more declarative syntax:

```yaml
- uses: cross-platform-actions/action@v0.28.0
  with:
    operating_system: haiku
    architecture: x86-64
    version: r1beta5
    environment_variables: CCACHE_DIR
    pre_run: |
      pkgman update -y && pkgman install -y ccache cmake git libao libsdl2 libzip lua miniupnpc ninja libcdio
    run: |
      cmake -B build -DUSE_LIBCDIO=ON -DCMAKE_BUILD_TYPE=Release -G Ninja
      cmake --build build --config Release
```

If the `pre_run` parameter is present it would run the command first, then reboot the VM and finally run the regular `run` command. If the `pre_run` parameter is **not** present it would behave as it does today.

**Comment by manxorist** [comment]
I guess option 1 would be more flexible: i.e. if the required dependencies are stored in the repository itself, the pkgman command line would not be statically known inside the action.

**Comment by jacob-carlborg** [comment]
>  if the required dependencies are stored in the repository itself, the pkgman command line would not be statically known inside the action.

Not sure I follow.

**Comment by Xottab-DUTY** [comment]
> > If pre_run would run before syncing files is possible (which I assumed), then this use case is not solvable with option 2.
> 
> It would run in the same place `run` is run today. `run` would then run later stage, after the reboot.
> 
> > Also, when we consider building Haiku packages (not my use case, but a possible use case for sure) and testing these packages, it might require a second reboot after the just-built package gets installed, in order to run tests with it afterwards.
> 
> That's a good point. I'm just not sure if it's possible to implement the first alternative. Perhaps if this feature is implemented: [#83](https://github.com/cross-platform-actions/action/issues/83).

Yep, the first one is better. It should be easy to implement: basically, CPA already runs commands using `exec`, we just need to save them into `.sh` script and that's it.

**Comment by jacob-carlborg** [comment]
@scribam do you mind testing the `custom-shell-83-2` branch? It has support for a new reboot script. Just run `cpa-reboot.sh`.

**Comment by scribam** [comment]
@jacob-carlborg Is it `cpa-reboot.sh` or `cpa.sh --reboot`? Do I have to use this custom shell in order to run the shell script?
```
    defaults:
      run:
        shell: cpa.sh {0}
```

**Comment by jacob-carlborg** [comment]
> Is it cpa-reboot.sh or cpa.sh --reboot

@scribam It's `cpa.sh --reboot` now.

> Do I have to use this custom shell in order to run the shell script?

No. It should run on the host. You can combine it with the custom shell.

See this test for examples:
https://github.com/cross-platform-actions/action/blob/37c06f011da89cd15ca49699b5fd0981b34d4065/.github/workflows/ci.yml#L622-L675

**Comment by scribam** [comment]
The reboot step is working but I have an issue with CMake. It looks like the executable is not found but the `$PATH` contains the directory where cmake is located.

Input:
```
- name: CMake
  run: |
    echo $PATH
    ls -al /boot/system/bin/cmake 2>&1 || true
    which cmake >/dev/null && cmake --version || echo "cmake not found"
    cmake -B build -DUSE_LIBCDIO=ON -DCMAKE_BUILD_TYPE=Release -G Ninja -DLIBRETRO=OFF
    cmake --build build --config Release
  shell: cpa.sh {0}
```
Output:
```
Pseudo-terminal will not be allocated because stdin is not a terminal.
.:/boot/home/config/non-packaged/bin:/boot/home/config/bin:/boot/system/non-packaged/bin:/boot/system/bin:/bin:/boot/system/apps:/boot/system/preferences
-r-xr-xr-x 1 user root 19597144 Apr 24 06:15 /boot/system/bin/cmake
cmake not found
Error: Process completed with exit code 4.
```
https://github.com/scribam/flycast/actions/runs/25236124189/job/74002604559

**Comment by jacob-carlborg** [comment]
> The reboot step is working but I have an issue with CMake. It looks like the executable is not found but the `$PATH` contains the directory where cmake is located.

Hmm, it's difficult to say. Does `cmake` work if you use the full path?

**Comment by scribam** [comment]
It looks like the command `cpa.sh --reboot` does not work correctly on Haiku 🤔 
Here is what I can see on freebsd:
```
Rebooting VM...
Pseudo-terminal will not be allocated because stdin is not a terminal.
Connection to cross_platform_actions_host closed by remote host.
Waiting for VM to come back up...
VM is ready
```
and on Haiku, I have:
```
Rebooting VM...
Pseudo-terminal will not be allocated because stdin is not a terminal.
usage: shutdown [-rqca] [-d time]
	-r reboot,
	-q quick shutdown (don't broadcast apps),
	-a ask user to confirm the shutdown (ignored when -q is given),
	-c cancel a running shutdown,
	-s run shutdown synchronously (only returns if shutdown is cancelled)
	-d delay shutdown by <time> seconds.
Waiting for VM to come back up...
VM is ready.
```
The usage displayed on Haiku suggests the shutdown command does not have the correct arguments hence the reboot is not done.

**Comment by jacob-carlborg** [comment]
@scribam I think that should be fixed now. Please give it another try.

**Comment by scribam** [comment]
Thank you, reboot works now! Unfortunately, even when using the full path to the cmake binary, I still have the same error: "Error: Process completed with exit code 4."

**Comment by jacob-carlborg** [comment]
Do you think it's a problem specific to Cross-Platform Action?

**Comment by scribam** [comment]
No idea, I don't know Haiku enough... `pkgman full-sync` and `pkgman update` don't work either, jobs are ended as they have exceeded the maximum execution time of 6h0m0s

**Comment by jacob-carlborg** [comment]
I tried compiling a simple Hello World with CMake on Haiku and it seems to work: https://github.com/cross-platform-actions/action/actions/runs/25368595604/job/74385854652. Doesn't require a reboot.

**Comment by scribam** [comment]
I did more tests and my error disappeared when I do not install the `curl_devel` package.
